kind: Service
apiVersion: v1
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
  - protocol: TCP
    port: 8888
    
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  selector:
      matchLabels:
        app: config-server
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: config-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8888